name: Build and Upload APK

on:
  push:
    branches: [ main ]  # 或者你的主分支名称
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleRelease  #  构建 debug APK，你可以改为 assembleRelease 构建 release 版本
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-apk  # 你可以自定义 artifact 的名字
        path: app/build/outputs/apk/debug/*.apk # 替换为你的 APK 输出路径
    - name: Publish Pre-Release
      uses: softprops/action-gh-release@v2
      with:
         files: |
            app/build/outputs/apk/debug/*.apk
         tag_name: ${{ github.ref }}
         release_name: Release ${{ github.ref }}
